name: Update README and Images

on: 
  workflow_dispatch:

jobs:
  update-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install dependencies
        run: |
          pip install matplotlib seaborn pandas numpy

      - name: Run script to generate README and images
        run: python generate_readme_and_images.py
      
      - name: Set blanch name as env variable
        run: echo "BRANCH_NAME=release/$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b ${{ env.BRANCH_NAME }}
          git add README.md
          git add images/*.png
          git commit -m "Update README and images"
          git push origin ${{ env.BRANCH_NAME }}
      
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: ${{ env.BRANCH_NAME }}
          destination_branch: "main"
          pr_title: "Update README and Images"
          pr_body: "Automated update of README and image files"
          pr_label: "automated pr"
